apiVersion: v1
kind: ResourceQuota
metadata:
  name: "compute-resources"
spec:
  hard:
# The sum of CPU requests across all pods in a non-terminal state cannot exceed
# this value. cpu and requests.cpu are the same value and can be used
# interchangeably.
    requests.cpu: "-1"
# The sum of memory requests across all pods in a non-terminal state cannot
# exceed this value. memory and requests.memory are the same value and can be
# used interchangeably.
    requests.memory: "-1Gi"
# The sum of ephemeral storage requests across all pods in a non-terminal state
# cannot exceed this value. ephemeral-storage and requests.ephemeral-storage are
# the same value and can be used interchangeably. This resource is available
# only if you enabled the ephemeral storage technology preview. This feature is
# disabled by default.
#    requests.ephemeral-storage: "1Gi" 
# The sum of CPU limits across all pods in a non-terminal state cannot exceed
# this value.
    limits.cpu: "-1"
# The sum of memory limits across all pods in a non-terminal state cannot exceed
# this value.
    limits.memory: "-1Gi"
# The sum of ephemeral storage limits across all pods in a non-terminal state
# cannot exceed this value. This resource is available only if you enabled the
# ephemeral storage technology preview. This feature is disabled by default.
#    limits.ephemeral-storage: "6Gi"
#  scopes:
#    - NotTerminating
