apiVersion: v1
kind: ResourceQuota
metadata:
  name: "object-counts-managed-resources"
spec:
  hard:
# The total number of pods in a non-terminal state that can exist in the project
    pods: "30" 
# The total number of replication controllers that can exist in the project
    replicationcontrollers: "20"
# The total number of resource quotas that can exist in the project
    resourcequotas: "5"
# The total number of services that can exist in the project
    services: "10"
# The total number of secrets that can exist in the project
    secrets: "50"
# The total number of ConfigMap objects that can exist in the project
    configmaps: "10"
# The total number of persistent volume claims that can exist in the project
    persistentvolumeclaims: "5"
# The total number of image streams that can exist in the project.
    openshift.io/imagestreams: "10"
